# Generated by Django 4.2.8 on 2023-12-20 19:26

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import myapp.models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(validators=[myapp.models.validate_age])),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('middle_name', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(default='default@example.com', max_length=254, validators=[django.core.validators.RegexValidator(message='Email must end with @ur.ac.rw', regex='.*@ur.ac.rw$')])),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=13, region=None)),
                ('reference_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(99, message='Reference number must be between 99 and 999'), django.core.validators.MaxValueValidator(999, message='Reference number must be between 99 and 999')])),
                ('gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('O', 'Other')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=30)),
                ('model', models.CharField(max_length=30)),
                ('plate_number', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid plate number with exactly one letter after the numbers.', regex='^(RA[ABCDEFGH]|(RNP|RDF|GR|IT|CD))[0-9]{3}[0-9A-HJ-NP-Y]{1}$')])),
                ('manufacture_date', models.IntegerField(validators=[myapp.models.validate_manufacture_date])),
                ('color', models.CharField(max_length=20)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='myapp.participant')),
            ],
        ),
    ]
